name: Staged Images

on:
  workflow_dispatch:
    inputs:
      image_group:
        description: "Which staged image set to build"
        type: choice
        required: true
        default: all
        options:
          - all
          - kbs
          - as
          - kbs-client
          - rvps
  pull_request:
    branches: ["main"]
    paths-ignore:
      - '**/*.md'

permissions: {}

jobs:
  build_staged_images_pr:
    name: Build staged images (all) [PR]
    if: github.event_name == 'pull_request'
    permissions:
      contents: read
    uses: ./.github/workflows/workflow-call-build-staged-images-pr.yml
    with:
      image_group: all

  build_staged_images_push:
    name: Build staged images (manual)
    if: github.event_name == 'workflow_dispatch'
    permissions:
      packages: write
      contents: read
    uses: ./.github/workflows/workflow-call-build-staged-images-push.yml
    with:
      image_group: ${{ inputs.image_group }}
    secrets:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}

  publish_manifests:
    name: Publish multi-arch manifests
    needs: build_staged_images_push
    if: github.event_name == 'workflow_dispatch' && inputs.image_group == 'all'
    permissions:
      packages: write
      contents: read
    uses: ./.github/workflows/workflow-call-publish-staged-manifests.yml
    with:
      tags: '["kbs","kbs-grpc-as","coco-as-grpc","coco-as-restful","rvps","kbs-client-image"]'
    secrets:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}
